Streaming timeline printer
DanielaSfregola/twitter4s-demo pull request #20
Opened 2017-10-30 18:59 UTC by darkrodry

Demo to print the user timeline in real time and cherry pick of some refactors from the previous PR https://github.com/DanielaSfregola/twitter4s-demo/pull/18

2017-10-31 11:38 UTC, DanielaSfregola commented on README.md
> +- [TweetTimelineStreamPrinter](https://github.com/DanielaSfregola/twitter4s-demo/blob/master/src/main/scala/streaming/TweetTimelineStreamPrinter.scala) print the tweets in your timeline using stream.
You should also add a description for SampleStatusesHashtagPrinter

2017-10-31 11:41 UTC, DanielaSfregola requested changes
Hi @darkrodry,
thanks for your contribution!

Only minor comments and a description missing in the README.

Once these are fixed, we are good to go!

2017-10-31 11:41 UTC, DanielaSfregola commented on src/main/scala/streaming/SampleStatusesHashtagPrinter.scala
>    val client = TwitterStreamingClient()
I would add the same TODO comment for consistency:
`// TODO - Make sure to define your consumer and access tokens!`

2017-11-05 19:29 UTC, darkrodry commented
Changes are ready!

2017-11-06 10:19 UTC, DanielaSfregola approved these changes
Hi @darkrodry,
thanks for the changes and thanks for your contribution!

LGTM

2017-11-06 10:19 UTC, merged